cache:
  paths:
    - /root/.m2/repository

stages:
  - build
  - test

build:
  stage: build
  image: maven:3.6.3-openjdk-15
  script:
    - echo $SPRING_DATASOURCE_PASSWORD
    - echo $SPRING_DATASOURCE_URL
    - echo $SPRING_DATASOURCE_USERNA
    - mvn package -B
  tags:
    - docker

test:
  stage: test
  image: maven:3.6.3-openjdk-15
  script:
    - mvn test
  tags:
    - docker